import { humanize } from '../lib/format.js';

// Thin outlined pills. Colour carries meaning; the text always says it too.
const TONES = {
  neutral: 'text-muted border-line-strong',
  accent: 'text-accent border-accent/35 bg-accent/[0.06]',
  ok: 'text-ok border-ok/30 bg-ok/[0.05]',
  info: 'text-info border-info/30 bg-info/[0.05]',
  caution: 'text-caution border-caution/30 bg-caution/[0.05]',
  warn: 'text-warn border-warn/35 bg-warn/[0.05]',
  danger: 'text-danger border-danger/35 bg-danger/[0.06]',
};

export function Badge({ tone = 'neutral', title, children, className = '' }) {
  return (
    <span
      title={title}
      className={`inline-flex h-5 items-center gap-1 whitespace-nowrap rounded-(--radius-chip) border px-1.5 font-mono text-[10.5px] uppercase tracking-[0.06em] ${TONES[tone]} ${className}`}
    >
      {children}
    </span>
  );
}

const STATUS_TONE = {
  pending_analysis: 'neutral',
  awaiting_review: 'accent',
  auto_cleared: 'ok',
  resolved: 'neutral',
  appeal_pending: 'warn',
  appeal_resolved: 'neutral',
};
export function StatusBadge({ status }) {
  return <Badge tone={STATUS_TONE[status] ?? 'neutral'}>{humanize(status)}</Badge>;
}

const ACTION_TONE = { none: 'ok', label: 'caution', limit: 'warn', remove: 'danger' };
export function ActionBadge({ action, title }) {
  if (!action) return <span className="text-subtle">—</span>;
  return (
    <Badge tone={ACTION_TONE[action]} title={title}>
      {action}
    </Badge>
  );
}

const SEVERITY_TONE = { none: 'neutral', low: 'info', medium: 'caution', high: 'danger' };
export function SeverityBadge({ severity, title }) {
  if (!severity) return <span className="text-subtle">—</span>;
  return (
    <Badge tone={SEVERITY_TONE[severity]} title={title}>
      {severity}
    </Badge>
  );
}

const VISIBILITY_TONE = { visible: 'ok', labeled: 'caution', limited: 'warn', removed: 'danger' };
export function VisibilityBadge({ visibility }) {
  return <Badge tone={VISIBILITY_TONE[visibility]}>{visibility}</Badge>;
}

export function VersionBadge({ version, prefix = '' }) {
  if (version == null) return null;
  return (
    <Badge tone="neutral" title={`Policy version ${version}`}>
      {prefix}v{version}
    </Badge>
  );
}

/** Every piece of AI-generated text carries this label. */
export function AiLabel() {
  return (
    <Badge tone="accent" title="Generated by the AI reviewer. A human makes the decision.">
      AI suggestion
    </Badge>
  );
}
